CREATE TABLE IF NOT EXISTS covid_symptoms (
  id INT AUTO_INCREMENT PRIMARY KEY,
  Fever VARCHAR(255) NOT NULL,
  Tiredness VARCHAR(255) NOT NULL,
  'Dry-Cough' VARCHAR(255) NOT NULL,
  'Difficulty-in-Breathing' VARCHAR(255) NOT NULL,
  'Sore-Throat' VARCHAR(255) NOT NULL,
  'None_Sympton' VARCHAR(255) NOT NULL,
  Pains VARCHAR(255) NOT NULL,
  'Nasal-Congestion' VARCHAR(255) NOT NULL,
  'Runny-Nose' VARCHAR(255) NOT NULL,
  Diarrhea VARCHAR(255) NOT NULL,
  'None_Experiencing' VARCHAR(255) NOT NULL,
  'Age_0-9' VARCHAR(255) NOT NULL,
  'Age_10-19' VARCHAR(255) NOT NULL,
  'Age_20-24' VARCHAR(255) NOT NULL,
  'Age_25-59' VARCHAR(255) NOT NULL,
  'Age_60+' VARCHAR(255) NOT NULL,
  'Gender_Female' VARCHAR(255) NOT NULL,
  'Gender_Male' VARCHAR(255) NOT NULL,
  'Gender_Transgender' VARCHAR(255) NOT NULL,
  'Severity_Mild' VARCHAR(255) NOT NULL,
  'Severity_Moderate' VARCHAR(255) NOT NULL,
  'Severity_None' VARCHAR(255) NOT NULL,
  'Severity_Severe' VARCHAR(255) NOT NULL,
  'Contact_Dont-Know' VARCHAR(255) NOT NULL,
  'Contact_No' VARCHAR(255) NOT NULL,
  'Contact_Yes' VARCHAR(255) NOT NULL,
  Country VARCHAR(255) NOT NULL
);
